using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Dreamy.Feedback.Editor
{
    public static class FeedbackIdsGenerator
    {
        private const string OutputFolder = "Assets/DreamyFeedbackGenerated";

        public static void GenerateSelected()
        {
            EnsureOutputFolder();
            var generatedAny = false;
            for (var i = 0; i < Selection.objects.Length; i++)
            {
                var selected = Selection.objects[i];
                if (selected is VfxDatabase vfxDatabase)
                {
                    Write("VfxIds.cs", GenerateClass("VfxIds", Collect(vfxDatabase)));
                    generatedAny = true;
                }
                else if (selected is FloatingTextDatabase floatingTextDatabase)
                {
                    Write("FloatingTextIds.cs", GenerateClass("FloatingTextIds", Collect(floatingTextDatabase)));
                    generatedAny = true;
                }
                else if (selected is CameraShakeDatabase cameraShakeDatabase)
                {
                    Write("CameraShakeIds.cs", GenerateClass("CameraShakeIds", Collect(cameraShakeDatabase)));
                    generatedAny = true;
                }
                else if (selected is FeedbackSequenceDatabase sequenceDatabase)
                {
                    Write("FeedbackSequenceIds.cs", GenerateClass("FeedbackSequenceIds", Collect(sequenceDatabase)));
                    generatedAny = true;
                }
            }

            if (!generatedAny)
            {
                Debug.LogWarning("Select one or more Dreamy Feedback databases before generating IDs.");
            }

            AssetDatabase.Refresh();
        }

        public static string GenerateClass(string className, IEnumerable<string> ids)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("namespace Dreamy.Feedback.Generated");
            sb.AppendLine("{");
            sb.Append("    public static class ").AppendLine(className);
            sb.AppendLine("    {");
            var usedNames = new HashSet<string>();
            foreach (var id in ids)
            {
                if (string.IsNullOrWhiteSpace(id))
                {
                    continue;
                }

                var name = FeedbackUtility.ToPascalIdentifier(id);
                var uniqueName = name;
                var suffix = 2;
                while (!usedNames.Add(uniqueName))
                {
                    uniqueName = name + suffix;
                    suffix++;
                }

                sb.Append("        public const string ").Append(uniqueName).Append(" = \"").Append(Escape(id)).AppendLine("\";");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static IEnumerable<string> Collect(VfxDatabase database)
        {
            for (var i = 0; i < database.Entries.Count; i++)
            {
                yield return database.Entries[i]?.Id;
            }
        }

        private static IEnumerable<string> Collect(FloatingTextDatabase database)
        {
            for (var i = 0; i < database.Entries.Count; i++)
            {
                yield return database.Entries[i]?.Id;
            }
        }

        private static IEnumerable<string> Collect(CameraShakeDatabase database)
        {
            for (var i = 0; i < database.Presets.Count; i++)
            {
                yield return database.Presets[i]?.Id;
            }
        }

        private static IEnumerable<string> Collect(FeedbackSequenceDatabase database)
        {
            for (var i = 0; i < database.Entries.Count; i++)
            {
                yield return database.Entries[i]?.Id;
            }
        }

        private static void EnsureOutputFolder()
        {
            if (!AssetDatabase.IsValidFolder(OutputFolder))
            {
                AssetDatabase.CreateFolder("Assets", "DreamyFeedbackGenerated");
            }
        }

        private static void Write(string fileName, string contents)
        {
            var path = Path.Combine(OutputFolder, fileName).Replace("\\", "/");
            File.WriteAllText(path, contents, Encoding.UTF8);
            Debug.Log($"Generated feedback IDs: {path}");
        }

        private static string Escape(string value)
        {
            return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }
    }
}
