using System;
using System.Linq;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Dreamy.Feedback.Editor
{
    public static class FeedbackIdsGenerator
    {
        private const string OutputFolder = "Assets/DreamyFeedbackGenerated";

        public static void GenerateSelected()
        {
            var grouped = new Dictionary<string, List<string>>();
            foreach (var selected in Selection.objects)
            {
                if (selected is VfxDatabase vfx) CollectInto(grouped, "VfxIds", Collect(vfx));
                else if (selected is FloatingTextDatabase text) CollectInto(grouped, "FloatingTextIds", Collect(text));
                else if (selected is CameraShakeDatabase shake) CollectInto(grouped, "CameraShakeIds", Collect(shake));
                else if (selected is FeedbackDefinition definition) CollectInto(grouped, "FeedbackIds", new[] { definition.Id });
            }
            if (grouped.Count == 0)
            {
                Debug.LogWarning("Select one or more Dreamy Feedback databases before generating IDs.");
                return;
            }
            EnsureOutputFolder();
            foreach (var pair in grouped)
                Write(pair.Key + ".cs", GenerateClass(pair.Key, pair.Value.Distinct(StringComparer.Ordinal).OrderBy(id => id, StringComparer.Ordinal)));

            AssetDatabase.Refresh();
        }

        private static void CollectInto(Dictionary<string, List<string>> grouped, string name, IEnumerable<string> ids)
        {
            if (!grouped.TryGetValue(name, out var list)) { list = new List<string>(); grouped.Add(name, list); }
            list.AddRange(ids);
        }

        public static string GenerateClass(string className, IEnumerable<string> ids)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("namespace Dreamy.Feedback.Generated");
            sb.AppendLine("{");
            sb.Append("    public static class ").AppendLine(className);
            sb.AppendLine("    {");
            var usedNames = new HashSet<string>();
            foreach (var id in ids)
            {
                if (string.IsNullOrWhiteSpace(id))
                {
                    continue;
                }

                var name = FeedbackUtility.ToPascalIdentifier(id);
                var uniqueName = name;
                var suffix = 2;
                while (!usedNames.Add(uniqueName))
                {
                    uniqueName = name + suffix;
                    suffix++;
                }

                sb.Append("        public const string ").Append(uniqueName).Append(" = \"").Append(Escape(id)).AppendLine("\";");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static IEnumerable<string> Collect(VfxDatabase database)
        {
            for (var i = 0; i < database.Entries.Count; i++)
            {
                yield return database.Entries[i]?.Id;
            }
        }

        private static IEnumerable<string> Collect(FloatingTextDatabase database)
        {
            for (var i = 0; i < database.Entries.Count; i++)
            {
                yield return database.Entries[i]?.Id;
            }
        }

        private static IEnumerable<string> Collect(CameraShakeDatabase database)
        {
            for (var i = 0; i < database.Presets.Count; i++)
            {
                yield return database.Presets[i]?.Id;
            }
        }

        private static void EnsureOutputFolder()
        {
            if (!AssetDatabase.IsValidFolder(OutputFolder))
            {
                AssetDatabase.CreateFolder("Assets", "DreamyFeedbackGenerated");
            }
        }

        private static void Write(string fileName, string contents)
        {
            var path = Path.Combine(OutputFolder, fileName).Replace("\\", "/");
            File.WriteAllText(path, contents, Encoding.UTF8);
            Debug.Log($"Generated feedback IDs: {path}");
        }

        private static string Escape(string value)
        {
            return value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\r", "\\r").Replace("\n", "\\n").Replace("\t", "\\t").Replace("\0", "\\0");
        }
    }
}
